name: artifact

on: [push]

env:
  FILE_NAME: hello-server

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read file
      run: |
        cd ./scripts
        chmod +x *.sh
        ./compile.sh
      shell: bash
      run: |
        cd ./scripts
        ls