name: artifact

on: [push]

env:
  FILE_NAME: hello-server

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List all the project
        run: |
          ls
        shell: bash
      - name: Print branch name
        run: echo running on branch ${GITHUB_REF##*/}